### ISSUE TITLE
No audio inputs working

### ISSUE THREAD

**Issue by songproducer** [kritzikratzi/Oscilloscope#59] opened 2018-07-16 18:37 UTC
Using an apollo twin mkii sound card on mac sierra, tried both versions and tried default settings.

**Comment by sonicuse** [comment] 2019-04-11 10:26
I have the same problem. Just with the RME soundcard

**Comment by kritzikratzi** [comment] 2019-08-15 15:14
duplicate of #62

**Closed by kritzikratzi** 2019-08-15 15:14 UTC
